[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "karlproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=4.2.23",
    "pymysql>=1.1.1",
    "requests>=2.32.5",
    "uwsgi>=2.0.30; sys_platform != 'win32'",
    "pycryptodome>=3.23.0",
    "pytz>=2025.2",
    "requests>=2.32.5",
]

[tool.setuptools]
packages = ["KarlProject", "ShuaBu"]
