# Generated by Django 4.2.23 on 2025-08-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShuaBu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='step',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
